{{- if and (.Values.karpenter.enable) (.Values.karpenter-provisioner.enable) (.Values.karpenter-provisioner) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-provisioner
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/karpenter-provisioner
    targetRevision: {{ .Values.targetRevision }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.karpenter.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  {{- end -}}
