apiVersion: v1
kind: Secret
metadata:
  name: gitlab-rails-storage
  namespace: gitlab
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: ap-southeast-1
    use_iam_profile: true
---
apiVersion: v1
data:
  config: czM6CiAgYnVja2V0OiBicG0tZmVjcmVkaXQtZGV2LWdpdGxhYi1yZWdpc3RyeQogIHJlZ2lvbjogYXAtc291dGhlYXN0LTEKICB2NGF1dGg6IHRydWU=
kind: Secret
metadata:
  name: registry-storage
  namespace: gitlab
type: Opaque
---
apiVersion: v1
data:
  config: W2RlZmF1bHRdCmJ1Y2tldF9sb2NhdGlvbiA9IGFwLXNvdXRoZWFzdC0x
kind: Secret
metadata:
  name: storage-config
  namespace: gitlab
type: Opaque